# Question 1
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [15]:
import numpy as np
np.arange(2,50,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

# Question 2
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [19]:
lst1 = []
lst2 = []

for i in range(5):
    num1 = int(input())
    lst1.append(num1)
    
for i in range(5):
    num2 = int(input())
    lst2.append(num2)
    
arr1 = np.array(lst1)
print("arr1 = ",arr1)
arr2 = np.array(lst2)
print("arr2 = ",arr2)
arrcon = np.concatenate((arr1, arr2))
print("arrcon = ",arrcon)
arrcon.sort()
print("arrsort = ",arrcon)

5
4
3
2
1
0
9
8
7
6
arr1 =  [5 4 3 2 1]
arr2 =  [0 9 8 7 6]
arrcon =  [5 4 3 2 1 0 9 8 7 6]
arrsort =  [0 1 2 3 4 5 6 7 8 9]


# Question 3
Write a code snippet to find the dimensions of a ndarray and its size.

In [28]:
arr1 = np.arange(1,4)
arr2 = np.arange(1,13).reshape((3, 4))
arr3 = np.arange(1,25).reshape((2, 3, 4))

print(arr1)
print("arr1 dimensions = ",arr1.ndim,"\narr1 size = ",arr1.size,"\n\n")
print(arr2)
print("arr2 dimensions = ",arr2.ndim,"\narr2 size = ",arr2.size,"\n\n")
print(arr3)
print("arr3 dimensions = ",arr3.ndim,"\narr3 size = ",arr3.size)

[1 2 3]
arr1 dimensions =  1 
arr1 size =  3 


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
arr2 dimensions =  2 
arr2 size =  12 


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
arr3 dimensions =  3 
arr3 size =  24


# Question 4
How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet

In [42]:
x = np.zeros((3, 4)) 
y = np.expand_dims(x, axis=1)
print(x.shape)
print(y.shape) 

(3, 4)
(3, 1, 4)


In [39]:
arr = np.arange(5*5).reshape(5,5) 
print(arr.shape) 
  
newaxes = (0, 3, -1) 
arr_5D = np.expand_dims(arr, axis=newaxes) 
print(arr_5D.shape)

(5, 5)
(1, 5, 5, 1, 1)


# Question 5
Consider two square numpy arrays. Stack them vertically and horizontally.

In [60]:
arr3 = np.arange(1,4)
arr4 = np.arange(4,7)
print("arr1 = ",arr3)
print("arr2 = ",arr4)

hstak = np.hstack((arr3, arr4)) 
print("\n\nHorizontally stacked:\n",hstak)
vstak = np.vstack((arr3, arr4)) 
print("\nVertically stacked:\n",vstak)

arr1 =  [1 2 3]
arr2 =  [4 5 6]


Horizontally stacked:
 [1 2 3 4 5 6]

Vertically stacked:
 [[1 2 3]
 [4 5 6]]


# Question 6
How to get unique items and counts of unique items?

In [72]:
lst = np.array([1,1,1,1,1,1,1,2,2,3,3,3,3,3,4,4,4,4,4,4,5,5,5,6,6,6,6,7,7,7,7,7,7,7])
print('Original array: ' ,lst)

print("\nWe can get the unique values of the list by using the numpy unique function\n")

uniqueValues, occurCount = np.unique(lst, return_counts=True)
print("Unique Values : " , uniqueValues)
print("Occurrence Count : ", occurCount)

Original array:  [1 1 1 1 1 1 1 2 2 3 3 3 3 3 4 4 4 4 4 4 5 5 5 6 6 6 6 7 7 7 7 7 7 7]

We can get the unique values of the list by using the numpy unique function

Unique Values :  [1 2 3 4 5 6 7]
Occurrence Count :  [7 2 5 6 3 4 7]
